project:
  type: website

website:
  title: "FOSS Tools for FOSS Development"
  site-url: https://ns-rse.github.io/foss-tools-for-foss-dev
  description: "Quarto RevealJS Slides for a SSI Fellowship Application on using the Free Open Source Software Emacs for development of Free Open Source Software."
